-include ../Makefile.credentials
include ../Makefile.deploytemplate

WORKFLOW_NAME=template_nf_workflow
TOOL_FOLDER_NAME=template_nf_workflow
WORKFLOW_VERSION=release_30
WORKFLOW_DESCRIPTION="Template workflow for NextFlow in ProteoSAFe"
